- hosts: nextcloud_servers
  vars_files:
    - config_vars.yml

  roles:
    - nc_prepare
    - nc_configure_php
    - nc_postgres
    - nc_nextcloud
    - role: nc_selfsignedcert
      when: with_selfsigned
    - role: nc_certbot
      when: not with_selfsigned
    - role: nc_apache
      when: not with_hiawatha
    - role: nc_hiawatha
      when: with_hiawatha
    - nc_rsync

- hosts: webmail_servers
  vars_files:
    - config_vars.yml
  roles:
    - role: wm_roundcube

    - role: nc_selfsignedcert
      when: with_selfsigned

    - role: wm_conf_apache
      when: not with_hiawatha

    - role: wm_conf_hiawatha
      when: with_hiawatha
