---
# tasks file for nc_certbot
- name: Install letsencrypt configuration
  unarchive:
    # make sure letsencrypt.tar.gz is the newest possible
    src: letsencrypt.tar.gz
    dest: /etc
  become: yes

- name: Install certbot package
  apt:
    name: certbot
    state: latest
  become: yes

- set_fact:
    main_cert_dir: /etc/letsencrypt/live
    cert_dir:  "/etc/letsencrypt/live/{{inventory_hostname}}"
    cert_only_name: "/etc/letsencrypt/live/{{inventory_hostname}}/fullchain.pem"
    cert_key: "/etc/letsencrypt/live/{{inventory_hostname}}/privkey.pem"
- set_fact:
    cert_name: "{{cert_dir}}/key_plus_cert.pem"
