---
# tasks file for nc_prepare
- name: Upgrade the system packages
  apt:
     update-cache: yes
     upgrade: full
     autoremove: yes
     cache_valid_time: 86400
  become: yes

- name: Install package dependencies
  apt:
     state: latest
     name: "{{ needed_packages }}"
  become: yes

- name: Check PHP version
  shell: ls /etc/php | tail -1
  register: phpoutput
- set_fact:
     php_version: "{{ phpoutput.stdout_lines[0] }}"
