---
# tasks file for nc_selfsignedcert
- name: Ensure certificates directory
  become: yes
  file:
     dest: "{{cert_dir}}/"
     state: directory
     mode: 0700

- name: Generate an OpenSSL private key.
  become: yes
  openssl_privatekey:
    path: "{{cert_key}}"

- name: Generate an OpenSSL CSR.
  become: yes
  openssl_csr:
    path: "{{cert_dir}}/request.csr"
    privatekey_path: "{{cert_key}}"
    common_name: "{{ server_hostname }}"

- name: Generate a Self Signed OpenSSL certificate.
  become: yes
  openssl_certificate:
    path: "{{cert_only_name}}"
    privatekey_path: "{{cert_key}}"
    csr_path: "{{cert_dir}}/request.csr"
    provider: selfsigned

- name: Create final cert with key and cert
  become: yes
  shell: cat {{cert_key}} {{cert_only_name}} > {{cert_name}}
